site_name: Content Interface
site_url: https://djplaner.github.io/Content-Interface-Tweak/
site_author: David Jones
site_description: >-
  Assemblage of technologies to enable use of Microsoft Word for content creation and updating for Blackboard Learn

# Configuration
theme:
  name: material

  language: en
#  features:
#    - tabs

nav:
  - Home: 'index.md'
  - Background: 
    - What & Why: 'background/whatWhy.md'
    - How does it work: 'background/howWorks.md'
  - Using:
    - Authoring set up: 'using/authoringSetup.md'
    - Page set up: 'using/setup.md'
    - Create and modify: 'using/createAndModify.md'
    - Automating updates: 'using/automatingUpdates.md'
    - Sync shared folder: 'using/syncSharedFolder.md'
  - Creating:
    - Textual: 'creating/textualContent.md'
    - Web: 'creating/webContent.md'
    - University: 'creating/universityContent.md'
    - Blackboard: 'creating/blackboardContent.md' 
    - Adding Cards: 'creating/addCards.md' 
  - Customising:
    - Accordion opening: 'customising/accordionOpening.md'
    - Accordion appearance: 'customising/accordionAppearance.md'
    - Content appearance: 'customising/contentAppearance.md'
    - Provide PDF: 'customising/providePDF.md'
    - Download Button: 'customising/downloadButton.md'
markdown_extensions:
  - toc:
      permalink: '#'
      baselevel: 1
